apiVersion: v1
kind: Service
metadata:
  name: springboot-web-svc
  namespace: dev
spec:
  ports: 
  - port: 80
    targetPort: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: springboot-web
 