#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubbo-demo
spec:
  selector:
    matchLabels:
      app: dubbo-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: dubbo-demo
    spec:
      hostNetwork: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dubbo-demo
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: dubbo-demo
          image: 192.168.243.138/kubernetes/dubbo-demo:v1
          ports:
            - containerPort: 20880
