apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  namespace: dev
spec:
  hostNetwork: true
  #使用宿主机的pid namespace
  hostPID: true
  hostAliases:
  - ip: "192.168.254.129"
    hostnames:  
    - "web.weng.com"
  containers:
  - name: web
    image: 192.168.254.131/k8s/web:v1
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-web
    lifecycle:
      postStart:
        exec:
          command:  ["/bin/bash","-c","echo web starting ... >> /var/log/messages"]
      preStop:
        exec:
          command:  ["/bin/bash","-c","echo web stopping ... >> /var/log/messages"]
  - name: dubbo
    env:
    - name: DUBBO_PORT
      value: "20881"
    image: 192.168.254.131/k8s/dubbo:v1
    ports:
    - containerPort: 20881
      hostPort: 20881
      protocol: TCP
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-dubbo
  #pod层面的定义，所有pod里面的容器都可以使用volumes
  volumes:
  - name: shared-volume
    hostPath:
      path: /shared-volume-data
     
