apiVersion: v1
kind: Pod
metadata:
  name: pod-network
  namespace: dev
spec:
  containers:
  - name: web
    image: 192.168.254.131/k8s/web:v1
    ports:
    - containerPort: 8080
  - name: dubbo
    env:
    - name: DUBBO_PORT
      value: "20881"
    image: 192.168.254.131/k8s/dubbo:v1
    ports:
    - containerPort: 20881
      hostPort: 20881
      protocol: TCP
     