apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-system
  labels:
    name: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 80
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: kube-system
spec:
  rules:
    - host: kibana.weng.com
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 80
---
#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: kibana
  replicas: 1
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        image: registry.cn-hangzhou.aliyuncs.com/imooc/kibana:5.5.1
        env:
        - name: CLUSTER_NAME
          value: docker-cluster
        - name: ELASTICSEARCH_URL
          value: http://eelasticsearch-api:9200/
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m       
        ports:
        - containerPort: 5601
          name: http