#deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
  namespace: test
spec:
  selector:
    matchLabels:
      app: web-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
      - name: web-demo
        image: 192.168.254.131/k8s/web:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
          #不加单位默认是字节数
            memory: 2000Mi
            #不加m，表示100核心的cpu，100个cpu,1核心cpu == 1000m
            cpu: 3000m
          limits:
            memory: 3000Mi
            cpu: 4000m
